#!/bin/bash
yum update -y
yum install -y httpd24 php70 mysql56-server php70-mysqlnd
service httpd start
chkconfig httpd on
groupadd www
usermod -a -G www ec2-user
chown -R ec2-user:apache /var/www
chmod 2775 /var/www
find /var/www -type d -exec sudo chmod 2775 {} +
find /var/www -type f -exec sudo chmod 0664 {} +
cd /var/www/html
aws s3 cp s3://rivwox/lt.jpg lt.jpg
aws s3 cp s3://rivwox/index.html index.html
aws s3 cp s3://rivwox/com.png com.png
